Remove empty `tests` script which trips up Pipenv >2022.9.20
Pipenv 2022.9.20 was just realeased, and they updated dependencies for Pipfile parsing to `plette`.
This results in a Schema validation error for the existing Pipfile, due to an empty value for the script `tests`.

```
pipenv.vendor.plette.models.base.ValidationError: {'__script__': ''}
__script__: empty values not allowed
```

This PR fixes that by removing the unusued `tests` script declaration from Pipenv.
After this change, Pipenv 2022.9.20 runs successfully.